export const FB_AUTH = 'fb_auth';
export const GOOGLE_AUTH = 'google_auth';
export const LOGIN_USER = 'login_user';
export const GET_COORDINATES = 'get_coordinates';
export const GET_RESTAURANTS = 'get_restaurants';
export const GET_RESTAURANTS_DETAILS = 'get_restaurants_details';
export const LOG_OUT ='log_out';
export const SAVE_BOOKMARK = 'save_bookmark';
export const GET_BOOKMARKS = 'get_bookmarks';